### ISSUE TITLE
Nested Diff/Support for sections in UIKit utils

### ISSUE THREAD

**Issue by wokalski** [wokalski/Diff.swift#14]
Diffing trees is a hard problem and the best algorithms out there take `O(n^3)` time to compute.
However diffing content separated into sections is a very well defined problem and it doesn't require anything near as complicated as tree diffing.

A function with this signature would be enough:
```swift
func nestedDiff<T: Collection>(from: T, to: T) -> NestedDiff 
where T.Iterator.Element: Collection, 
T.Iterator.Element.Iterator.Element: Equatable
````

1. The function flatMaps the input and output and memorises the indices at which the separate collections start/end. 
2. a normal diff is performed on the flatMapped collection
3. it is mapped back into the nested diff.

When this is implemented it will be easy to add an overload on the UIKit utility functions. if the arguments to `animateRowChanges` are nested collections it will to perform the animations.

**Comment by farzadshbfn** [comment]
Isn't it better to use something like this?
`public extension Collection where Iterator.Element: Collection, Iterator.Element.Iterator.Element: Equatable {
	func nestedDiff<T: Collection>(to: T) -> NestedDiff
	where T.Iterator.Element: Collection,
		T.Iterator.Element.Iterator.Element: Equatable
}`

**Comment by wokalski** [comment]
yes, it will be more consistent.

**Comment by kaandedeoglu** [comment]
>1. The function flatMaps the input and output and memorises the indices at which the separate collections start/end.
>2. a normal diff is performed on the flatMapped collection
>3. it is mapped back into the nested diff.

I'm confused about something...

how would you handle the case where the sections are initially:

section 0 = [a, b, c]
section 1 = [d, e, f]

and are finally:

section 0 = [a, b]
section 1 = [c, d, e, f]

the flatMapped collections look identical so diffing would not yield any results.

Am I missing something?

**Comment by wokalski** [comment]
Good point. I think that given count of each section you can split them accordingly.
Does this make sense ?

**Comment by kaandedeoglu** [comment]
I understand the general idea of it yes. Just finished implementing "reset to defaults" functionality for a 2 section reoderable collection view using `Diff.swift` but had cases which I could not handle. So I had to fall back to `reloadData()` rather than `performBatchUpdates` for those special cases. 

I'm sure this is doable but did not work for me using `ExtendedDiff` and doing the `look at the initial/final array counts to calculate sections` dance. Here's another counter-example that made me fail:

initial:
[a, b, c, d, e] [f, g, h]

final:
[a, b, e] [c, d, f, g, h]

When looking at the ExtendedDiff of the merged arrays, the result would just tell you to move `e` from index 2 to 4. But in reality you would need more moves to to put everything back to normal.

**Comment by wokalski** [comment]
I don't understand the example. Could you elaborate with outputs? Also, I am more than happy to help you with this on your fork if you want.

**Comment by kaandedeoglu** [comment]
First of all, thank you for all your time :)

I've made two screenshots describing two different collection view states.

# STATE 1
![a](https://cloud.githubusercontent.com/assets/1566836/21012999/11612d9a-bd61-11e6-9b75-be10d06b5d41.png)

# STATE 2
![b](https://cloud.githubusercontent.com/assets/1566836/21013070/4f5e0550-bd61-11e6-9302-32581a6b34b9.png)

My objective is to find all the moves that get me from State2 back to State1.

If you flatMap and then compare two data sources. They would look like the ones below:

State 1: [A, B, C, D, E, F, G, H]

State 2: [A, B, E, C, D, F, G, H]

`ExtendedDiff`ing them would give `.move(from: 2, to: 5)`. But that wouldn't be enough in `performBatchUpdates`, I would need `.move(from: 3, to: 2)` and `.move(from: 4, to: 3)` to get back to State1.

I hope this was clear, please tell me if I'm wrong, or overcomplicating things.

**Comment by wokalski** [comment]
@farzadshbfn Are you sure that it tells you to move from 2 to 5? and not 4? If so, it's a serious bug.

I believe that one move is enough:
- from: (index: 2, section: 0)
- to: (index: 4, section: 0)

----

Basically the second step is to convert to proper section. In order to do that you have to look at the counts of sections in the _target_ collection.

**Comment by kaandedeoglu** [comment]
Yes sorry it would tell me to move from 2 to 4. But imagine reordering the collection view in a performBatch updates block. To go from State 2 to State 1, you would need 2 moves, because you want to move both `C` and `D` from section 2 to section 1.

**Comment by wokalski** [comment]
Ah, I see. Yeah, you are right! So after successful first step, we need to do additional dance with moves according to changes of count in relative sections

**Comment by kaandedeoglu** [comment]
I'd love to see how you handle it! I will also try to come up with an elegant solution and let you know if I have anything. Just felt weird to push it too much inside a UIViewController method.

**Comment by wokalski** [comment]
if you'd like, create a fork with what you have and I'll collaborate.

**Comment by wokalski** [comment]
Yeah, don't put too much in the view controller 🗡

**Comment by wokalski** [comment]
This issue is taken care of in #27

**Comment by wokalski** [comment]
@kaandedeoglu 
This is my solution using the aforementioned algorithm (still with some cases unresolved). I didn't go with this approach, though. It was just redundant complexity.

https://gist.github.com/wokalski/ac371168e920e649037fd368d3d60bd3
