### ISSUE TITLE
Travis builds fail

### ISSUE THREAD

**Issue by wokalski** [wokalski/Diff.swift#19]
Travis builds fail because of a timeout? (supposedly)

**Comment by wokalski** [comment]
There's a job failing usually on iPad Air 2. It might be that in fact there are some edge cases where the diff output is wrong. Worth investigation.

**Comment by tonyarnold** [comment]
Was this fixed by the addition of `sleep 5` to the bottom of the `after_success` section of the TravisCI configuration? Looks like most of the recent pull request builds are passing OK now.

**Comment by wokalski** [comment]
[Unfortunately not](https://travis-ci.org/wokalski/Diff.swift/jobs/191206827)

Travis issue:
https://github.com/travis-ci/travis-ci/issues/6675
