### ISSUE TITLE
How to specify Diff.swift as a dependency via Swift Package Manager?

### ISSUE THREAD

**Issue by tonyarnold** [wokalski/Diff.swift#29]
Using the following dependency specifier:

```swift
.Package(url: "https://github.com/wokalski/Diff.swift.git", versions: Version(0, 4, 0)..<Version(1, 0, 0))
```

I'm unable to include Diff.swift as a dependency via Swift PM. I get the following error:

```
error: No version tag found in (/Users/tonyarnold/Documents/Repositories/SomeProject/Packages/Diff.swift.git) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"
```

I _think_ that Swift PM expects [SemVer](http://semver.org/), which would mean you need to tag with the full `major.minor.patch` (so `0.4.0` rather than `0.4).

**Comment by tonyarnold** [comment]
For pre-release versions, I believe you should be using `1.0.0-beta.1`.

**Comment by wokalski** [comment]
You are [right](https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#version). Well, it looks like trying to be too smart gets back at me again. 

I think that we should change the versioning scheme to semver. 

will it mess cocoapods/Carthage up? Probably not but I might be missing something.

**Comment by tonyarnold** [comment]
As long as you stick to strict SemVer, Carthage & CocoaPods will cope.

**Comment by wokalski** [comment]
Yeah. I was just thinking about some edge cases with compatibility with existing specs/cartfiles. I will release a dummy 0.4.1 version which fixes this today.

**Comment by tonyarnold** [comment]
Hi @wokalski do you have any objections to me creating the dummy 0.4.1 release? I've [suggested via a PR changes to Bond's diffing](https://github.com/ReactiveKit/Bond/issues/346) to remove the custom implementation and replace it with yours, but Swift PM compatibility will be broken until the Diff.swift 0.4.1 release is out. 

There's no urgency to this at all, I just have a little spare time over the next night or two.

**Comment by wokalski** [comment]
sure :shipit:. I didn't computer during Christmas and forgot about it. Sorry about this.

**Comment by tonyarnold** [comment]
Done in 1091e96c33e4a1f41fac35ced9be9640c214263c. Thanks, @wokalski and enjoy the rest of your break!
