### ISSUE TITLE
Can we release v0.4 to CocoaPods?

### ISSUE THREAD

**Issue by srdanrasic** [wokalski/Diff.swift#30]
Hi @wokalski,

Thanks for such useful library! We've just integrated it in ReactiveKit/Bond as a dependency, replacing our simple algorithm, but we are using v0.4 that's unfortunately not released over CocoaPods.

Would it be possible to push v0.4 to CocoaPods?

Thanks!

**Comment by wokalski** [comment]
Fixed in 262d1ccf1c6ba538f933246fc60c75d76d3abb35 🎁. I released the newest version.
