### ISSUE TITLE
Cannot compile with Swift 3.1p1 

### ISSUE THREAD

**Issue by wokalski** [wokalski/Diff.swift#39]
It's a compiler regression spotted by @tonyarnold. It's [on Swift's JIRA](https://bugs.swift.org/browse/SR-3707).

You can work around the issue by commenting out public `extendedPatch` method

**Comment by tonyarnold** [comment]
So the original SR-3707 was resolved by Apple engineers, however there are now multiple other (very similar) issues in SourceKitService with the same method:

- https://bugs.swift.org/browse/SR-3707
- https://bugs.swift.org/browse/SR-3815
