### ISSUE TITLE
How do i get a list of inserted items from a patch/diff?

### ISSUE THREAD

**Issue by SuperTango** [wokalski/Diff.swift#40]
I'm using Diff for the normal UITableView functionality that you provide, but I also have a case where I have two lists and need to perform an action for every new and deleted element. 

For example: 
 
        let currentUsers = ["A", "B", "C"]
        let newUsers = ["A", "D", "F", "C", "G"]
        let diff = currentUsers.diff(newUsers)
        let patch = diff.patch(from: currentUsers, to: newUsers)

        // what I want to do:
        for user in patch.inserted {
            // Send notification that there is a new user.
        }

I've fished around the source, but haven't really found how to do it.

**Comment by SuperTango** [comment]
Maybe if you could just explain how to get any information out of diff.elements, that'd be a good start.  Thanks.

**Comment by wokalski** [comment]
Are you familiar with the difference between [diff and patch](https://github.com/wokalski/Diff.swift#diff-vs-patch-sorting)? In your use case you would just enumerate the diff using `for in` and switch inside it to check if it's an insertion or deletion.

all suggestions regarding the documentation are welcome.
