### ISSUE TITLE
Potential Xcode 8.3 issues

### ISSUE THREAD

**Issue by wokalski** [wokalski/Diff.swift#45]
The [`typealias` workaround](https://github.com/wokalski/Diff.swift/pull/44/commits/cb3e640b1fcc7ac1d59ab7d1cdd5acccc4bf4fb4#diff-dfa1d29c6d22504ce140d084c8fa326fR9) might not be required in Xcode 8.3.

**Comment by tonyarnold** [comment]
It _may_ not be: https://github.com/apple/swift/pull/7640

However, the duplicate `typealias`es should be removed once the project is Swift 3.1 and later only.

**Comment by tonyarnold** [comment]
🎉
