### ISSUE TITLE
BatchUpdate access level.

### ISSUE THREAD

**Issue by sunshinejr** [wokalski/Diff.swift#52]
Hey! First of all thanks for the awesome library 🎉 

I just wanted to ask if it would be possible to change `BatchUpdate` access level to `public`? We use it quite often so in my [Swift 2.3 fork](https://github.com/sunshinejr/Diff.swift/tree/swift-2.3) I've made it public, but it might've been a bad idea considering I didn't ask if we can do the same for the main repo and the future transition from Swift 2.3 to 3.X might be more problematic than needed :D If not I will just reverse the changes and include copy of the struct in the project, so no worries there :)

Cheers!

**Comment by wokalski** [comment]
When/when do you use it?

**Comment by sunshinejr** [comment]
This struct is helpful when we want to extract insertions/deletions/moves and pass it to our own table view updater. We use our own because e.g. we don't want to use animations or we want to do something when animation completes.

**Comment by sunshinejr** [comment]
Sure! Gonna do :)

**Comment by sunshinejr** [comment]
Closing in favor of #53.
