### ISSUE TITLE
animateRowAndSectionChanges only works inside didSet for my Model

### ISSUE THREAD

**Issue by erickva** [wokalski/Diff.swift#54]
I have Diff (animateRowAndSectionChanges) working using the didSet for my Model, but I want to be able to use somewhere else in my code

 I have a delegate method being triggered whenever my Model is updated, at this stage I need to manually call the animateRowAndSectionChanges, but it does not work even though I am passing the same values for old and new.

**Comment by wokalski** [comment]
Maybe the contents of the table view differ? It is weird indeed. Are you able to provide me with a minimal reproducible example?

**Comment by erickva** [comment]
Please open the workspace:
https://ufile.io/5jk1i

This works fine:
```
var model = [Section]() {
        didSet {
            self.swapModels(old: oldValue, new: self.model)
        }
    }
```
But if I remove the didSet and use the method ```swapModels``` found in the bottom of the VC.swift (```func receiveModel(model: [Section])``` and ```func refreshModel(model: [Section])```) and comment the self.model = model, it does not work.

**Comment by wokalski** [comment]
So your delegates depend on `self.model` so when you make the moves they use invalid data. They should use `new` data from the delegate call in order to make it work.

**Comment by erickva** [comment]
Fundamental error, thanks @wokalski !
