### ISSUE TITLE
Xcode 9 beta compiling

### ISSUE THREAD

**Issue by makos88** [wokalski/Diff.swift#56]
Hello!

I have trouble with compiling library into Xcode 9 - beta.
When I want to build project I got this errors:
![screen shot 2017-06-19 at 15 11 13](https://user-images.githubusercontent.com/3307752/27298860-946d9de8-552a-11e7-9478-b62dddca5553.png)

Are you expecting to update your library to resolve this issue?

**Comment by wokalski** [comment]
Swift 4? @tonyarnold has WIP here: https://github.com/wokalski/Diff.swift/pull/55

**Comment by makos88** [comment]
@tonyarnold when will it be finish?

**Comment by tonyarnold** [comment]
@makos88 you can try out my `swift-4.0` branch now if you're working under Xcode 9. It _should_ be fine, but I'm not using it on anything right now so please let me know here if you find anything broken. 

It won't be done until Xcode 9.0 is released.

**Comment by makos88** [comment]
@tonyarnold I see only master branch. I don't see your `swift-4.0` branch

**Comment by tonyarnold** [comment]
It's in my fork: https://github.com/tonyarnold/Diff.swift/tree/swift-4.0

**Comment by makos88** [comment]
@tonyarnold great. It works now :)

**Comment by mecid** [comment]
@wokalski could you please merge this fork into main repo?

**Comment by tonyarnold** [comment]
As noted in #64, I'm going to be maintaining a separate fork going forward. I'm just deciding on a new name and tidying everything up - my hope is that I'll be ready to finish this up tonight, then I'll work with Bond to switch over to this new fork. 

My fork will (initially) be source compatible with this project, so you shouldn't need to change anything except the pod you're depending on.
