### ISSUE TITLE
Memory leak in DoublyLinkedList

### ISSUE THREAD

**Issue by bstrull** [wokalski/Diff.swift#57]
I'm using Diff through Bond/ReactiveKit and have memory leaks due to the DoublyLinkedList as called from Diff.shiftedPatchElements, called from Diff.ExtendedDiff.patch.    I get a 2 node cycle between next and previous.

Doesn't previous need to be declared weak to avoid a retain cycle?

**Comment by farzadshbfn** [comment]
How come we never noticed it 🤔... You're absolutely right.

**Comment by wokalski** [comment]
Fixed by #58.
